// Automatically generated by astro-icon
// 7ce5866cd816d26b76ecabfacf802205e54cde0850fd683e5b4c1014383117d4

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "ion:earth"
		| "ion:logo-github"
		| "ion:logo-twitter"
		| "ion:logo-linkedin"
		| "ion:logo-instagram"
		| "ion:logo-youtube"
		| "lucide:briefcase-business"
		| "lucide:command"
		| "lucide:house"
		| "lucide:library"
		| "lucide:mail-plus"
		| "lucide:monitor-cog"
		| "lucide:notebook-pen"
		| "lucide:palette"
		| "lucide:pen-line"
		| "lucide:rss"
		| "lucide:square-user"
		| "lucide:home"
		| "ri:quill-pen-fill"
		| "simple-icons:astro"
		| "tabler:alert-circle"
		| "arrow-up"
		| "github"
		| "mail"
		| "mastodon"
		| "menu"
		| "moon"
		| "pause"
		| "play"
		| "sun"
		| "system";
}