// Automatically generated by astro-icon
// dfe4be46e67597808e918f2dcfc5b4d78f2adcf866116158e000050b9a346fad

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "ion:earth"
		| "ion:logo-github"
		| "ion:logo-twitter"
		| "ion:logo-linkedin"
		| "ion:logo-instagram"
		| "ion:logo-youtube"
		| "lucide:briefcase-business"
		| "lucide:command"
		| "lucide:house"
		| "lucide:library"
		| "lucide:mail-plus"
		| "lucide:monitor-cog"
		| "lucide:notebook-pen"
		| "lucide:palette"
		| "lucide:pen-line"
		| "lucide:rss"
		| "lucide:square-user"
		| "lucide:home"
		| "ri:quill-pen-fill"
		| "tabler:alert-circle"
		| "pause"
		| "play";
}