services:
  site:
    env_file:
      - .env.production
    ports:
      - "3000:3000" # Expose to host (or reverse proxy)
    environment:
      NODE_ENV: production
      PUBLIC_API_URL: https://api.yourdomain.com

  api:
    env_file:
      - .env.production
    ports:
      - "8080:8080" # Expose to host (or reverse proxy)
    environment:
      RUST_LOG: warn
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

  db:
    env_file:
      - .env.production
