packages:
  - apps/*
  - packages/*

catalog:
  "@dotenvx/dotenvx": ^1.52
  "@total-typescript/ts-reset": ^0.6.1
  "@types/node": ^24
  eslint: ^9.39.2
  prettier: ^3.8.1
  tsx: ^4.21.0
  typescript: ^5.9.3

catalogMode: manual

onlyBuiltDependencies:
  - "@parcel/watcher"
  - unrs-resolver
  - esbuild
