packages:
  - apps/*
  - packages/*

catalog:
<<<<<<< HEAD
  '@dotenvx/dotenvx': ^1.52
  '@total-typescript/ts-reset': ^0.6.1
  '@types/node': ^24
  '@typescript/native-preview': ^7.0.0-dev.20260202.1
=======
  "@dotenvx/dotenvx": ^1.52
  "@total-typescript/ts-reset": ^0.6.1
  "@types/node": ^24
>>>>>>> 64af84e65373887657c6f2b62e0b42f4ea4ea587
  eslint: ^9.39.2
  prettier: ^3.8.1
  tsx: ^4.21.0
  typescript: ^5.9.3

catalogMode: manual

onlyBuiltDependencies:
<<<<<<< HEAD
  - unrs-resolver
=======
  - "@parcel/watcher"
  - unrs-resolver
  - esbuild
>>>>>>> 64af84e65373887657c6f2b62e0b42f4ea4ea587
