packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@dotenvx/dotenvx": ^1.52
  "@total-typescript/ts-reset": ^0.6.1
  "@types/node": ^24
  "@typescript/native-preview": ^7.0.0-dev.20260202.1
  prettier: ^3.8.1
  tsx: ^4.21.0
  typescript: ^5.9.3

catalogMode: manual
