/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as dashboardIndexRouteImport } from './routes/(dashboard)/index'
import { Route as dashboardTransactionsRouteImport } from './routes/(dashboard)/transactions'
import { Route as dashboardPotsRouteImport } from './routes/(dashboard)/pots'
import { Route as dashboardBudgetsRouteImport } from './routes/(dashboard)/budgets'
import { Route as dashboardBillsRouteImport } from './routes/(dashboard)/bills'
import { Route as dashboard_layoutRouteImport } from './routes/(dashboard)/__layout'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'

const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: '/(dashboard)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardTransactionsRoute = dashboardTransactionsRouteImport.update({
  id: '/(dashboard)/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardPotsRoute = dashboardPotsRouteImport.update({
  id: '/(dashboard)/pots',
  path: '/pots',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardBudgetsRoute = dashboardBudgetsRouteImport.update({
  id: '/(dashboard)/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardBillsRoute = dashboardBillsRouteImport.update({
  id: '/(dashboard)/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboard_layoutRoute = dashboard_layoutRouteImport.update({
  id: '/(dashboard)/__layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/(auth)/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/bills': typeof dashboardBillsRoute
  '/budgets': typeof dashboardBudgetsRoute
  '/pots': typeof dashboardPotsRoute
  '/transactions': typeof dashboardTransactionsRoute
  '/': typeof dashboardIndexRoute
}
export interface FileRoutesByTo {
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/bills': typeof dashboardBillsRoute
  '/budgets': typeof dashboardBudgetsRoute
  '/pots': typeof dashboardPotsRoute
  '/transactions': typeof dashboardTransactionsRoute
  '/': typeof dashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(dashboard)/__layout': typeof dashboard_layoutRoute
  '/(dashboard)/bills': typeof dashboardBillsRoute
  '/(dashboard)/budgets': typeof dashboardBudgetsRoute
  '/(dashboard)/pots': typeof dashboardPotsRoute
  '/(dashboard)/transactions': typeof dashboardTransactionsRoute
  '/(dashboard)/': typeof dashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/signin'
    | '/signup'
    | '/bills'
    | '/budgets'
    | '/pots'
    | '/transactions'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/signup'
    | '/bills'
    | '/budgets'
    | '/pots'
    | '/transactions'
    | '/'
  id:
    | '__root__'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/(dashboard)/__layout'
    | '/(dashboard)/bills'
    | '/(dashboard)/budgets'
    | '/(dashboard)/pots'
    | '/(dashboard)/transactions'
    | '/(dashboard)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
  dashboard_layoutRoute: typeof dashboard_layoutRoute
  dashboardBillsRoute: typeof dashboardBillsRoute
  dashboardBudgetsRoute: typeof dashboardBudgetsRoute
  dashboardPotsRoute: typeof dashboardPotsRoute
  dashboardTransactionsRoute: typeof dashboardTransactionsRoute
  dashboardIndexRoute: typeof dashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/transactions': {
      id: '/(dashboard)/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof dashboardTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/pots': {
      id: '/(dashboard)/pots'
      path: '/pots'
      fullPath: '/pots'
      preLoaderRoute: typeof dashboardPotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/budgets': {
      id: '/(dashboard)/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof dashboardBudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/bills': {
      id: '/(dashboard)/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof dashboardBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/__layout': {
      id: '/(dashboard)/__layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboard_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
  dashboard_layoutRoute: dashboard_layoutRoute,
  dashboardBillsRoute: dashboardBillsRoute,
  dashboardBudgetsRoute: dashboardBudgetsRoute,
  dashboardPotsRoute: dashboardPotsRoute,
  dashboardTransactionsRoute: dashboardTransactionsRoute,
  dashboardIndexRoute: dashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
