/* !!! This is code generated by a script. Do not edit directly. !!! */
/** biome-ignore-all assist/source/organizeImports: generated file */
/** biome-ignore-all lint: generated file */
/* eslint-disable */
// @ts-nocheck
/*
 * This is a barrel export file for all the icons in this directory as React components.
 *
 * 🟢 You can import this file directly.
 * Generated on: Mon Jan 19 12:57:57 PM WAT 2026
 */
export { default as IconArrowFatLinesLeft } from "./arrow-fat-lines-left.svg";
export { default as IconArrowUpDown } from "./arrow-up-down.svg";
export { default as IconBarbell } from "./barbell.svg";
export { default as IconBookOpen } from "./book-open.svg";
export { default as IconCaretDown } from "./caret-down.svg";
export { default as IconCaretLeft } from "./caret-left.svg";
export { default as IconCaretRight } from "./caret-right.svg";
export { default as IconCaretUp } from "./caret-up.svg";
export { default as IconChartDonut } from "./chart-donut.svg";
export { default as IconCircleCheck } from "./circle-check.svg";
export { default as IconCircleWarning } from "./circle-warning.svg";
export { default as IconCircleX } from "./circle-x.svg";
export { default as IconEllipsis } from "./ellipsis.svg";
export { default as IconEyeSlash } from "./eye-slash.svg";
export { default as IconEye } from "./eye.svg";
export { default as IconFilter } from "./filter.svg";
export { default as IconHouse } from "./house.svg";
export { default as IconIllustrationAuthentication } from "./illustration-authentication.svg";
export { default as IconJarFillX } from "./jar-fill-x.svg";
export { default as IconJarFill } from "./jar-fill.svg";
export { default as IconListBullets } from "./list-bullets.svg";
export { default as IconLogoX } from "./logo-x.svg";
export { default as IconLogo } from "./logo.svg";
export { default as IconMagnifyingGlass } from "./magnifying-glass.svg";
export { default as IconMusicNote } from "./music-note.svg";
export { default as IconNetwork } from "./network.svg";
export { default as IconPottedPlant } from "./potted-plant.svg";
export { default as IconReceiptX } from "./receipt-x.svg";
export { default as IconReceipt } from "./receipt.svg";
export { default as IconShieldPlus } from "./shield-plus.svg";
export { default as IconSortX } from "./sort-x.svg";
export { default as IconSort } from "./sort.svg";
export { default as IconVideo } from "./video.svg";
export { default as IconWarehouse } from "./warehouse.svg";
export { default as IconWrench } from "./wrench.svg";
