services:
  postgres:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: api
      POSTGRES_USER: api
      POSTGRES_DB: api
    ports:
      - 5432:5432
  postgres_test:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: api_test
      POSTGRES_USER: api_test
      POSTGRES_DB: api_test
    ports:
      - 5433:5432
